services:
    api:
        build: ./api
        restart: unless-stopped
        ports:
            - 127.0.0.1:3000:3000
        env_file:
            - .env
        volumes:
            - ./api:/app
            - node_modules_api:/app/node_modules
        command: npm run ${NODE_ENV:-development}
        # command: tail -f /dev/null #idle container
    redis:
        image: redis:alpine
        restart: unless-stopped
volumes:
    node_modules_api:
